#!/bin/bash

echo "Opening Accessibility Settings..."
open "x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility"

echo ""
echo "================================================"
echo "Manual Steps Required:"
echo "================================================"
echo ""
echo "1. Click the lock icon (bottom left) and authenticate"
echo "2. Click the '+' button below the app list"
echo "3. Press Cmd+Shift+G to open 'Go to folder' dialog"
echo "4. Add these binaries one by one:"
echo ""
echo "   /opt/homebrew/bin/sketchybar"
echo "   /opt/homebrew/bin/borders"
echo "   /Applications/AeroSpace.app"
echo "   /Applications/Ghostty.app"
echo "   /Applications/Alacritty.app"
echo "   /Applications/Marta.app"
echo ""
echo "5. Enable the checkbox next to each one"
echo "6. Restart the services:"
echo ""
echo "   brew services restart felixkratz/formulae/sketchybar"
echo "   brew services restart felixkratz/formulae/borders"
echo "   aerospace reload-config"
echo ""
echo "================================================"
